version: "3"

services:
  
  webapp:
    build:
      context: .
      dockerfile: etc/Dockerfile
    container_name: webapp
    restart: on-failure
    environment:
      - DEBUG=False
    volumes:
      - staticfiles:/usr/src/app/staticfiles
  
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: on-failure
    ports:
      - 3031:3031
    depends_on:
      - webapp
    volumes:
      - ./etc/default.conf:/etc/nginx/conf.d/default.conf      
      - staticfiles:/usr/share/nginx/staticfiles

volumes:
  staticfiles:
