version: "3"

services:
  
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    restart: on-failure
    ports:
      - 3031:3031      
    environment:
      - DEBUG=False
    volumes:
      - ./staticfiles:/usr/src/app/staticfiles