# Generated by Django 3.0.5 on 2020-04-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Uníca'), (2, 'Selección multiple'), (3, 'Numerica')], default=1, verbose_name='Tipo'),
        ),
    ]
