# Generated by Django 3.0.5 on 2020-04-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200415_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='validity',
            new_name='expired_on',
        ),
    ]
