# Generated by Django 3.0.5 on 2020-04-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200415_1424'),
        ('data', '0003_auto_20200415_1255'),
    ]

    operations = [
    ]
