# Generated by Django 3.0.5 on 2020-04-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_merge_20200415_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True, verbose_name='campo requerido'),
        ),
    ]
