# Generated by Django 3.0.5 on 2020-04-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_question_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='facility',
            field=models.IntegerField(choices=[(1, 'México'), (2, 'Guatemala'), (3, 'Panamá'), (4, 'República Dominicana')], default=1, verbose_name='Sede'),
        ),
    ]
